targets:
  ubuntu-16.04:
  ubuntu-18.04:
buildpack: https://github.com/pl31/heroku-buildpack-conda.git
user: "heroku-jupyter"
group: "heroku-jupyter"
env:
  - HOME=/opt/heroku-jupyter
before:
  - mkdir /opt/heroku-jupyter
